spring.application.name=demo
spring.datasource.url=jdbc:postgresql://lidl-db.cluster-ctfv9a1dq6ql.ap-southeast-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Welcome#2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# this for if URL NOT FOUND 
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.servlet.multipart.enabled=true
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false


spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF


